export const apiData = {
  modules: [
    {
      name: "Mod 1",
      id: "10820961-71db-43aa-92f2-f2281bc8ad6e",
      enabled: true,
      order: 100,
      thumbnailUrl: "https://www.somesite.com/images/image-1.png",
      properties: [
        {
          title: "First Name",
          property: "firstName",
          order: 1,
          type: "string",
          isRequired: true,
          width: "half",
          propertyOrder: 100,
        },
        {
          title: "Last Name",
          property: "lastName",
          order: 2,
          type: "string",
          isRequired: true,
          width: "half",
          propertyOrder: 110,
        },
        {
          title: "Employment Organization",
          property: "organization",
          order: 3,
          type: "string",
          isRequired: true,
          propertyOrder: 120,
        },
        {
          title: "Email",
          property: "email",
          order: 4,
          type: "string",
          validator: "email",
          isRequired: true,
          width: "half",
          forceLinebreak: true,
          propertyOrder: 130,
        },
        {
          title: "Country",
          property: "country",
          order: 5,
          type: "lookup",
          lookup: "c05dcf0e-529f-4152-a752-6f5a61892e74",
          isRequired: true,
          width: "half",
          defaultLookupId: "cee90a86-ea42-4723-801b-568851296481",
          propertyOrder: 140,
        },
        {
          title: "Address",
          property: "address",
          order: 6,
          type: "string",
          width: "full",
        },
        {
          title: "Address2",
          property: "address2",
          order: 7,
          type: "string",
          width: "full",
        },
        {
          title: "City",
          property: "city",
          order: 8,
          type: "string",
          width: "half",
        },
        {
          title: "State",
          property: "state",
          order: 9,
          type: "lookup",
          lookup: "9d4cd01c-abbd-46f4-b8cd-2ddaab85d2e5",
          width: "half",
          parentLookup: "c05dcf0e-529f-4152-a752-6f5a61892e74",
        },
        {
          title: "Zip/Postal Code",
          property: "postalCode",
          order: 10,
          type: "string",
          width: "quarter",
          forceLinebreak: true,
          propertyOrder: 150,
        },
        {
          title: "Phone (with country code)",
          property: "phone",
          order: 11,
          type: "string",
          width: "half",
        },
        {
          title: "Phone Extension",
          property: "phoneExt",
          order: 12,
          type: "string",
          width: "quarter",
        },
        {
          title: "Password",
          property: "password",
          description:
            "Password must be at least 12 characters have at least 1 upper case, 1 lower case, 1 number and one special character from !@#$%&*()",
          order: 13,
          type: "string",
          validator: "password",
          newRecordOnly: true,
          width: "half",
        },
        {
          title: "Password(Again)",
          property: "password2",
          order: 14,
          type: "string",
          validator: "passwordVerification",
          newRecordOnly: true,
          width: "half",
        },
        {
          title: "RunningStatus",
          property: "runningStatus",
          type: "string",
          propertyOrder: 200,
        },
      ],
      inputs: [
        "73efa3a9-37d0-4513-ae2d-72e7df41d8da",
        "4f064d1a-d1c6-4340-983e-8f15b0cc2ee1",
      ],
      outputs: ["b90ff6c7-ad27-442a-a6e2-687329d24aab"],
    },
    {
      name: "Mod2",
      id: "73efa3a9-37d0-4513-ae2d-72e7df41d8da",
      enabled: true,
      order: 200,
      thumbnailUrl: "https://www.somesite.com/images/image-2.png",
    },
    {
      name: "Mod3",
      id: "4f064d1a-d1c6-4340-983e-8f15b0cc2ee1",
      enabled: true,
      order: 300,
      thumbnailUrl: "https://www.somesite.com/images/image-3.png",
    },
    {
      name: "Mod4",
      id: "b90ff6c7-ad27-442a-a6e2-687329d24aab",
      enabled: true,
      order: 400,
      thumbnailUrl: "https://www.somesite.com/images/image-4.png",
    },
  ],
  lookups: [
    {
      id: "c05dcf0e-529f-4152-a752-6f5a61892e74",
      label: "Countries",
      name: "country",
      children: [
        {
          label: "Argentina",
          id: "7c932b88-d164-4de3-a28c-7ea3b3548db5",
        },
        {
          label: "Australia",
          id: "eafbd96e-7d5b-4fa6-be8b-6879486fc738",
        },
        {
          label: "Canada",
          id: "cead1c3d-6a93-4247-81e2-b30e78040c0a",
        },
        {
          label: "UnitedStates",
          id: "cee90a86-ea42-4723-801b-568851296481",
        },
      ],
    },
    {
      id: "9d4cd01c-abbd-46f4-b8cd-2ddaab85d2e5",
      label: "States",
      name: "state",
      children: [
        {
          label: "Alabama",
          id: "85bdf12f-227b-40a4-b99a-064430bcede2",
        },
        {
          label: "Alaska",
          id: "277ee285-75bc-499c-8449-5ff12e3b476b",
        },
        {
          label: "Arizona",
          id: "d8be3ffd-8060-42f4-848f-774904300f1d",
        },
        {
          label: "Arkansas",
          id: "a65912fa-537b-44cd-be82-f5ca15aff0d2",
        },
      ],
    },
  ],
};
